export type Difficulty = "medio" | "difficile" | "impossibile";

export type Quiz = {
  id: string;
  difficulty: Difficulty;
  question: string;
  options: string[];
  answer: number;
  points: number;
  credits: number;
  explanation: string;
};

export const DIFFICULTY_LABEL: Record<Difficulty, string> = {
  medio: "Medio",
  difficile: "Difficile",
  impossibile: "Impossibile",
};

export const QUIZZES: Quiz[] = [
  {
    id: "m1",
    difficulty: "medio",
    question: "Più ne togli, più diventa grande. Cos'è?",
    options: ["Un buco", "Una torta", "Un palloncino", "Una montagna"],
    answer: 0,
    points: 10,
    credits: 5,
    explanation: "Più terra togli, più il buco cresce.",
  },
  {
    id: "m2",
    difficulty: "medio",
    question: "Ho città ma niente case, monti ma niente alberi, acqua ma niente pesci.",
    options: ["Un deserto", "Una mappa", "Un sogno", "Un museo"],
    answer: 1,
    points: 10,
    credits: 5,
    explanation: "È una mappa geografica.",
  },
  {
    id: "m3",
    difficulty: "medio",
    question: "Un contadino ha 17 pecore. Tutte tranne 9 scappano. Quante ne restano?",
    options: ["8", "9", "17", "0"],
    answer: 1,
    points: 12,
    credits: 6,
    explanation: "«Tutte tranne 9» significa che ne restano esattamente 9.",
  },
  {
    id: "m4",
    difficulty: "medio",
    question: "Cosa si rompe appena lo pronunci?",
    options: ["Un vetro", "Il silenzio", "Una promessa", "Un uovo"],
    answer: 1,
    points: 10,
    credits: 5,
    explanation: "Il silenzio si rompe quando parli.",
  },
  {
    id: "m5",
    difficulty: "medio",
    question: "Quale mese ha 28 giorni?",
    options: ["Solo febbraio", "Nessuno", "Tutti", "Febbraio e marzo"],
    answer: 2,
    points: 12,
    credits: 6,
    explanation: "Tutti i mesi hanno (almeno) 28 giorni.",
  },
  {
    id: "m6",
    difficulty: "medio",
    question: "Sono leggero come una piuma, ma nemmeno l'uomo più forte mi regge a lungo.",
    options: ["Il respiro", "Un pensiero", "Una nuvola", "Un sussurro"],
    answer: 0,
    points: 12,
    credits: 6,
    explanation: "Il respiro: trattenerlo a lungo è impossibile.",
  },
  {
    id: "d1",
    difficulty: "difficile",
    question: "Una mazza e una palla costano 1,10 €. La mazza costa 1 € più della palla. Quanto costa la palla?",
    options: ["0,10 €", "0,05 €", "0,15 €", "1,00 €"],
    answer: 1,
    points: 20,
    credits: 10,
    explanation: "Palla 0,05 € + mazza 1,05 € = 1,10 €.",
  },
  {
    id: "d2",
    difficulty: "difficile",
    question: "5 macchine fanno 5 pezzi in 5 minuti. Quanto ci mettono 100 macchine per 100 pezzi?",
    options: ["100 minuti", "20 minuti", "5 minuti", "50 minuti"],
    answer: 2,
    points: 20,
    credits: 10,
    explanation: "Ogni macchina fa un pezzo in 5 minuti, quindi sempre 5 minuti.",
  },
  {
    id: "d3",
    difficulty: "difficile",
    question: "Le ninfee raddoppiano ogni giorno e coprono il lago in 48 giorni. Quando ne coprono metà?",
    options: ["Giorno 24", "Giorno 47", "Giorno 36", "Giorno 46"],
    answer: 1,
    points: 22,
    credits: 11,
    explanation: "Se raddoppiano, il giorno prima (47) ne coprono metà.",
  },
  {
    id: "d4",
    difficulty: "difficile",
    question: "Ho chiavi ma nessuna serratura, spazio ma nessuna stanza. Cosa sono?",
    options: ["Una tastiera", "Un pianoforte a coda", "Un portachiavi", "Un hotel"],
    answer: 0,
    points: 18,
    credits: 9,
    explanation: "Una tastiera: ha i tasti (chiavi) e la barra spaziatrice.",
  },
  {
    id: "d5",
    difficulty: "difficile",
    question: "Sono sempre davanti a te ma non puoi vedermi. Cosa sono?",
    options: ["L'aria", "Il futuro", "Il vento", "L'ombra"],
    answer: 1,
    points: 18,
    credits: 9,
    explanation: "Il futuro è sempre davanti, ma invisibile.",
  },
  {
    id: "d6",
    difficulty: "difficile",
    question: "Se sorpassi il secondo classificato in una gara, in che posizione arrivi?",
    options: ["Primo", "Secondo", "Terzo", "Dipende"],
    answer: 1,
    points: 20,
    credits: 10,
    explanation: "Prendi il suo posto: sei secondo.",
  },
  {
    id: "i1",
    difficulty: "impossibile",
    question: "Un uomo vive al 20° piano. Sale in ascensore al 10° e poi a piedi, tranne quando piove. Perché?",
    options: [
      "L'ascensore si guasta",
      "È basso e arriva solo al tasto 10, ma con l'ombrello preme il 20",
      "Fa esercizio fisico",
      "Ha paura dei temporali",
    ],
    answer: 1,
    points: 35,
    credits: 18,
    explanation: "Classico: con l'ombrello raggiunge il pulsante del 20° piano.",
  },
  {
    id: "i2",
    difficulty: "impossibile",
    question: "Due porte, due guardie: una mente sempre, una dice sempre il vero. Una sola domanda per salvarti.",
    options: [
      "«Sei sincero?»",
      "«Qual è la porta giusta?»",
      "«Cosa direbbe l'altra guardia se le chiedessi la porta giusta?» e poi scegli l'altra",
      "«Quanti anni hai?»",
    ],
    answer: 2,
    points: 40,
    credits: 20,
    explanation: "La risposta indica sempre la porta sbagliata: scegli l'altra.",
  },
  {
    id: "i3",
    difficulty: "impossibile",
    question: "Quante volte al giorno le lancette di un orologio analogico si sovrappongono perfettamente?",
    options: ["24", "22", "12", "11"],
    answer: 1,
    points: 38,
    credits: 19,
    explanation: "22 volte in 24 ore (11 ogni 12 ore).",
  },
  {
    id: "i4",
    difficulty: "impossibile",
    question: "Hai 8 palline uguali, una più pesante. Quante pesate minime con una bilancia a due piatti?",
    options: ["1", "2", "3", "4"],
    answer: 1,
    points: 40,
    credits: 20,
    explanation: "Bastano 2 pesate dividendo in gruppi da 3, 3 e 2.",
  },
  {
    id: "i5",
    difficulty: "impossibile",
    question: "Una clessidra da 7 minuti e una da 4: come misuri esattamente 9 minuti?",
    options: [
      "7 + 4 - 2",
      "Avvii entrambe, quando finisce la 4 la giri, a 8 giri la 7 e al termine hai 9",
      "Giri la 4 due volte e aspetti",
      "Non è possibile",
    ],
    answer: 1,
    points: 42,
    credits: 21,
    explanation: "Sequenza classica delle clessidre: 7 + 2 = 9 minuti.",
  },
  {
    id: "i6",
    difficulty: "impossibile",
    question: "Cosa aumenta di valore quando lo capovolgi e lo dividi a metà?",
    options: ["Il numero 6", "Il numero 9", "Il numero 8", "Il numero 0"],
    answer: 0,
    points: 36,
    credits: 18,
    explanation: "6 capovolto è 9; diviso a metà (9/2) vale comunque più di 6/2... trabocchetto classico.",
  },
];

export const FREE_ORDER: Difficulty[] = ["medio", "medio", "difficile", "difficile", "impossibile"];
export const BONUS_ORDER: Difficulty[] = ["medio", "difficile", "impossibile"];
